import { getAllPublished } from '@/lib/notion';
import Head from 'next/head';
import Link from 'next/link';

import styles from './Home.module.css';

export default async function Home() {
  const posts = await getAllPublished();

  if (!posts) return <h1>No posts</h1>;

  return (
    <div className={styles.container}>
      <Head>
        <title>My Blog</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <link
          rel='icon'
          href='/favicon.ico'
        />
      </Head>
      <main className={styles.main}>
        <h1>Blog</h1>
        {posts?.map((post, index) => (
          <section key={index}>
            <div>
              <h2>
                <Link href={`/daisy/diary/${post.slug}`}>{post.title}</Link>
              </h2>
              <div>
                <div>{post.date}</div>
                <p>{post.description}</p>
              </div>
            </div>
          </section>
        ))}
      </main>
    </div>
  );
}
